# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydjango
      MYSQL_USER: mydjango_user
      MYSQL_PASSWORD: mydjango_password
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    expose:
      - 3306
